### ISSUE TITLE
BUG - Erro 403 ao assistir vídeos das olimpíadas

### ISSUE THREAD

**Issue by rokam** [olavopeixoto/plugin.video.brplay#155]
```
2021-07-24 03:54:48.178 T:220031 WARNING <general>: [plugin.video.brplay] - BR play 2.0.1 | Starting...
2021-07-24 03:54:48.179 T:220031 WARNING <general>: [plugin.video.brplay] - [BRplay] - PARAMS: {'action': 'generic', 'meta': '{"handler": "resources.lib.modules.globosat.player", "method": "playlive", "id": "9542709", "IsPlayable": true, "livefeed": true, "geofencing": false, "lat": "-15.7942", "long": " -47.8825", "live": true, "channel_id": "1996", "service_id": 6761, "program_id": null, "studio": "Canais Globo", "label": "[B]SporTV[/B][I] - Badminton[/I] (Ao Vivo)", "title": "[B]SporTV[/B][I] - Badminton[/I] (Ao Vivo)", "year": null, "country": [], "genre": "T\\u00f3quio 2020", "cast": [], "director": [], "writer": [], "credits": [], "mpaa": null, "tvshowtitle": "Badminton", "sorttitle": "Badminton", "tag": ["09:00 - 12:59", "Ao Vivo", "Evento esportivo"], "plot": "09:00 - 12:59 | Jogos Ol\\u00edmpicos - T\\u00f3quio 2020", "duration": 14399, "dateadded": "2021-07-24 09:00:00", "mediatype": "episode", "art": {"icon": "https://s2.glbimg.com/fZYA8iFnO_RjrMXHe0BEZ4k_LVQ=/285x285/https://s2.glbimg.com/ciuZTxh3qawvQZfROu8ul5mQDAc=/filters:fill(transparent,false)/https://i.s3.glbimg.com/v1/AUTH_d2470d85104948f09eee09d5028bee11/internal_photos/bs/2021/X/W/LXXKE5Qve845nPQl7Rxg/logos-sportv-globoplay-01-1-.png", "clearlogo": "https://s2.glbimg.com/fZYA8iFnO_RjrMXHe0BEZ4k_LVQ=/285x285/https://s2.glbimg.com/ciuZTxh3qawvQZfROu8ul5mQDAc=/filters:fill(transparent,false)/https://i.s3.glbimg.com/v1/AUTH_d2470d85104948f09eee09d5028bee11/internal_photos/bs/2021/X/W/LXXKE5Qve845nPQl7Rxg/logos-sportv-globoplay-01-1-.png", "fanart": "https://s02.video.glbimg.com/x1080/9542709.jpg", "thumb": "https://live-thumbs.video.globo.com/spov28a/snapshot/?v=1627107592", "tvshow.poster": "https://live-thumbs.video.globo.com/spov28a/snapshot/?v=1627107592"}, "sort": [21, [36, "%U"], [26, "%U"], [33, "%L"]], "overlay": 4, "playcount": 0, "content": "tvshows", "properties": {"ResumeTime": 0.0}}'}
2021-07-24 03:54:48.249 T:220031 WARNING <general>: [plugin.video.brplay] - Playing item...
2021-07-24 03:54:48.249 T:220031 WARNING <general>: [plugin.video.brplay] - _get_module: resources.lib.modules.globosat.player
2021-07-24 03:54:48.734 T:220031 WARNING <general>: [plugin.video.brplay] - Handling route with: Player.playlive
2021-07-24 03:54:48.734 T:220031 WARNING <general>: [plugin.video.brplay] - Globosat Play - play_stream: id=9542709 | meta={'handler': 'resources.lib.modules.globosat.player', 'method': 'playlive', 'id': '9542709', 'IsPlayable': True, 'livefeed': True, 'geofencing': False, 'lat': '-15.7942', 'long': ' -47.8825', 'live': True, 'channel_id': '1996', 'service_id': 6761, 'program_id': None, 'studio': 'Canais Globo', 'label': '[B]SporTV[/B][I] - Badminton[/I] (Ao Vivo)', 'title': '[B]SporTV[/B][I] - Badminton[/I] (Ao Vivo)', 'year': None, 'country': [], 'genre': 'Tóquio 2020', 'cast': [], 'director': [], 'writer': [], 'credits': [], 'mpaa': None, 'tvshowtitle': 'Badminton', 'sorttitle': 'Badminton', 'tag': ['09:00 - 12:59', 'Ao Vivo', 'Evento esportivo'], 'plot': '09:00 - 12:59 | Jogos Olímpicos - Tóquio 2020', 'duration': 14399, 'dateadded': '2021-07-24 09:00:00', 'mediatype': 'episode', 'art': {'icon': 'https://s2.glbimg.com/fZYA8iFnO_RjrMXHe0BEZ4k_LVQ=/285x285/https://s2.glbimg.com/ciuZTxh3qawvQZfROu8ul5mQDAc=/filters:fill(transparent,false)/https://i.s3.glbimg.com/v1/AUTH_d2470d85104948f09eee09d5028bee11/internal_photos/bs/2021/X/W/LXXKE5Qve845nPQl7Rxg/logos-sportv-globoplay-01-1-.png', 'clearlogo': 'https://s2.glbimg.com/fZYA8iFnO_RjrMXHe0BEZ4k_LVQ=/285x285/https://s2.glbimg.com/ciuZTxh3qawvQZfROu8ul5mQDAc=/filters:fill(transparent,false)/https://i.s3.glbimg.com/v1/AUTH_d2470d85104948f09eee09d5028bee11/internal_photos/bs/2021/X/W/LXXKE5Qve845nPQl7Rxg/logos-sportv-globoplay-01-1-.png', 'fanart': 'https://s02.video.glbimg.com/x1080/9542709.jpg', 'thumb': 'https://live-thumbs.video.globo.com/spov28a/snapshot/?v=1627107592', 'tvshow.poster': 'https://live-thumbs.video.globo.com/spov28a/snapshot/?v=1627107592'}, 'sort': [21, [36, '%U'], [26, '%U'], [33, '%L']], 'overlay': 4, 'playcount': 0, 'content': 'tvshows', 'properties': {'ResumeTime': 0.0}, 'meta': {...}}
2021-07-24 03:54:48.734 T:220031 WARNING <general>: [plugin.video.brplay] - [Globoplay Player] - GET https://router.video.globo.com/cdn?video_id=9542709&player_type=androidtv&video_type=Live&content_protection=widevine&quality=max&cdn=globo
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - {'thumbs_preview_base_url': 'https://live-thumbs.video.globo.com/spov28a/snapshot/', 'resource': {'_id': '9542709_androidtv_androidtv_hdr_androidtv_sdr_elsys_tv_hls', 'content_protection': {'type': 'widevine'}, 'drm_protection_enabled': False, 'sources': [{'auth_param_templates': {'query_string': 'h={{hash}}&k={{key}}&a={{openClosed}}&u={{user}}'}, 'cdn': 'globo', 'url': 'https://live-as-01-18.video.globo.com/d/c/400x/e/nl/s/hls-spov28a/playlist.m3u8', 'url_parts': {'scheme': 'https', 'domain': 'live-as-01-18.video.globo.com', 'path': '/d/c/400x/e/nl/s/hls-spov28a/playlist.m3u8', 'template': '{{scheme}}://{{domain}}{{path}}?h={{hash}}&k={{key}}&a={{openClosed}}&u={{user}}'}, 'pop': 'as', 'dai': False, 'asset_key': ''}], 'signal': 'spov28a', 'transmission_id': 4274, 'affiliate': {}}}
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - {'resource_id': '9542709_androidtv_androidtv_hdr_androidtv_sdr_elsys_tv_hls', 'id': '9542709', 'title': None, 'program': None, 'program_id': None, 'provider_id': None, 'channel': None, 'channel_id': None, 'category': None, 'subscriber_only': True, 'exhibited_at': None, 'player': 'androidtv', 'version': '1.1.24', 'url': 'https://live-as-01-18.video.globo.com/d/c/400x/e/nl/s/hls-spov28a/playlist.m3u8', 'query_string_template': 'h={{hash}}&k={{key}}&a={{openClosed}}&u={{user}}', 'thumbUri': None, 'encrypted': False, 'drm_scheme': None, 'protection_url': None, 'cdn': 'globo', 'subtitles': []}
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - INFO: {'resource_id': '9542709_androidtv_androidtv_hdr_androidtv_sdr_elsys_tv_hls', 'id': '9542709', 'title': None, 'program': None, 'program_id': None, 'provider_id': None, 'channel': None, 'channel_id': None, 'category': None, 'subscriber_only': True, 'exhibited_at': None, 'player': 'androidtv', 'version': '1.1.24', 'url': 'https://live-as-01-18.video.globo.com/d/c/400x/e/nl/s/hls-spov28a/playlist.m3u8', 'query_string_template': 'h={{hash}}&k={{key}}&a={{openClosed}}&u={{user}}', 'thumbUri': None, 'encrypted': False, 'drm_scheme': None, 'protection_url': None, 'cdn': 'globo', 'subtitles': []}
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - Signing resource: 9542709_androidtv_androidtv_hdr_androidtv_sdr_elsys_tv_hls
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - username/password set. trying to authenticate
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - POST https://login.globo.com/api/authentication/sdk
2021-07-24 03:54:49.048 T:220031 WARNING <general>: [plugin.video.brplay] - {'content-type': 'application/json; charset=UTF-8', 'accept': 'application/json, text/javascript', 'Accept-Encoding': 'gzip', 'Authorization': 'IIDToken com.globo.hydra|fb4w1X4Ljh1HNDRE6PiS_i:APA91bFUPBWHd1HhX6GFIe7npWapSUTZGvslN8cALCc3iF0JTSwEqyXhJJdF7mRusx32DE2ANI2yEHybkUS7ueYMs3ijaZio_zFV93HiL90X2Y1AOJa2J_7l_v06QEd6GEDcMy0F4aIh'}
2021-07-24 03:54:49.051 T:220031 WARNING <general>: [plugin.video.brplay] - RESULT FROM CACHE: globoplay
2021-07-24 03:54:49.051 T:220031 WARNING <general>: [plugin.video.brplay] - GLOBOPLAY AUTHENTICATION RESPONSE: 498
2021-07-24 03:54:49.051 T:220031 WARNING <general>: [plugin.video.brplay] - <Response [498]>
2021-07-24 03:54:49.052 T:220031 WARNING <general>: [plugin.video.brplay] - authentication error: Invalid token
2021-07-24 03:54:49.052 T:220031 WARNING <general>: [plugin.video.brplay] - GET https://security.video.globo.com/videos/9542709/hash?resource_id=9542709_androidtv_androidtv_hdr_androidtv_sdr_elsys_tv_hls&version=1.1.24&player=android
2021-07-24 03:54:49.263 T:220031 WARNING <general>: [plugin.video.brplay] - {'http_status_code': 403, 'message': 'Video is for subscribers only. Authorization required.', 'code': 'AUT'}
2021-07-24 03:54:49.267 T:220031   FATAL <general>: [plugin.video.brplay] - Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/player.py", line 69, in playlive
                                                       hash_token, user, credentials = self.sign_resource(info['provider_id'], info['resource_id'], id, info['player'], info['version'], cdn)
                                                     File "/home/kodi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/player.py", line 241, in sign_resource
                                                       raise Exception(message)
                                                   Exception: 403|Video is for subscribers only. Authorization required.

2021-07-24 03:54:49.268 T:220031 WARNING <general>: [plugin.video.brplay] - PLAYER ERROR: Exception('403|Video is for subscribers only. Authorization required.')
2021-07-24 03:54:49.268 T:220031 WARNING <general>: [plugin.video.brplay] - Finished Processing

```

**Comment by rokam** [comment]
Percebi que o erro acontece com quem tem acesso aos canais SporTV pelo canaisglobo e tenta assisti os sinais web que estão disponíveis pelo GloboPlay. Portanto não é um erro e sim uma feature que a globo quer ganhar 2x.
