### ISSUE TITLE
Erro: Globo Play sem acesso ao Globo Sat

### ISSUE THREAD

**Issue by leosmeira** [olavopeixoto/plugin.video.brplay#70]
Não consigo acessar o conteúdo da Globo Play, ao acessar "Canais sob Demanda", o erro abaixo ocorre.

O mesmo não acontece se eu vincular a minha conta da Globo Play com a conta da operadora na Globo Sat.

LibreElec 9 / Kodi 8 Leia Alpha3
plugin.video.brplay (Master)

```
ERROR: Traceback (most recent call last):
18:08:34.133 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/main.py", line 148, in run
18:08:34.140 T:1369178992   ERROR:     vod.Vod().get_vod_channels_directory()
18:08:34.141 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py", line 33, in get_vod_channels_directory
18:08:34.144 T:1369178992   ERROR:     channels = self.get_vod_channels()
18:08:34.144 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py", line 39, in get_vod_channels
18:08:34.145 T:1369178992   ERROR:     channels = cache.get(self.__get_vod_channels, 360, table="channels")
18:08:34.145 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/cache.py", line 48, in get
18:08:34.145 T:1369178992   ERROR:     r = function(*args)
18:08:34.145 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py", line 56, in __get_vod_channels
18:08:34.146 T:1369178992   ERROR:     channels += globosat.Indexer().get_vod()
18:08:34.146 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/indexer.py", line 64, in get_vod
18:08:34.146 T:1369178992   ERROR:     vod = self.get_authorized_channels()
18:08:34.146 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/indexer.py", line 59, in get_authorized_channels
18:08:34.147 T:1369178992   ERROR:     channels = cache.get(scraper.get_authorized_channels, 360, table="auth_channels")
18:08:34.147 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/cache.py", line 48, in get
18:08:34.147 T:1369178992   ERROR:     r = function(*args)
18:08:34.147 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/scraper_vod.py", line 29, in get_authorized_channels
18:08:34.149 T:1369178992   ERROR:     token = auth_helper.get_globosat_token()
18:08:34.149 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/auth_helper.py", line 18, in get_globosat_token
18:08:34.149 T:1369178992   ERROR:     return get_credentials()
18:08:34.150 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/auth_helper.py", line 12, in get_credentials
18:08:34.150 T:1369178992   ERROR:     credentials = authenticator().authenticate(username, password)
18:08:34.150 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/auth.py", line 38, in authenticate
18:08:34.150 T:1369178992   ERROR:     self.credentials = self._authenticate(username, password)
18:08:34.150 T:1369178992   ERROR:   File "/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/auth.py", line 80, in _authenticate
18:08:34.151 T:1369178992   ERROR:     credentials = cookies[self.GLOBOSATPLAY_TOKEN_ID]
18:08:34.151 T:1369178992   ERROR: KeyError: 'GST'
18:08:34.151 T:1360786288   ERROR: GetDirectory - Error getting plugin://plugin.video.brplay/?action=vodChannels
18:08:34.153 T:1938960400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.brplay/?action=vodChannels) failed
```

**Comment by digaogt** [comment]
É um requerimento do próprio site da Globo agora. Essa parte do código mostra que não conseguiu realizar a autentificação e que ele não está conseguindo gerar a lista de canais.

**Comment by leosmeira** [comment]
Mas como tenho acesso apenas ao conteúdo da Globo Play, sem ter acesso ao Globo Sat ? Já que o Globo Sat é apenas para assinantes de TV por assintura.

Isso era possível na versão 0.0.14

**Comment by CaioTheBrain** [comment]
É só cadastrar um novo usuário na Globo.com sem vinculá-lo a uma assinatura de TV, e então usar esse usuário para logar no BR Play.

**Comment by leosmeira** [comment]
Já tenho um usuário da Globo.com com assinatura da Globo Play. Mas este
erro acorre.

Em dom, 22 de jul de 2018 13:57, CaioTheBrain <notifications@github.com>
escreveu:

**Comment by olavopeixoto** [comment]
Por favor envie o log completo com a opção Debug habilitada no Addon

**Comment by radbr** [comment]
Muito obrigado e parabens pelo repositorio. Gostaria de saber se é possivel desvincular a autenticação do premiere play da autenticação da operadora. A globo disponibilizou a venda da assinatura do premiere pelo globo.com, independente de operadora. Eu tenho apenas a do premiere e não está ocorrendo a autenticação. Obrigado

**Comment by leosmeira** [comment]
O problema foi resolvido no commit:

https://github.com/olavopeixoto/plugin.video.brplay/commit/79c2dc2728c7c6db2186d7835318b7e530e2b399
